In [27]:
import pandas as pd
import re

In [28]:
df = pd.read_csv("raw_data.csv")
df.head()

,Place ID,Nama Tempat,Alamat,Jenis Bisnis,Rating,Jumlah Review,Jam Operasional,Harga Start,Harga End,Latitude,Longitude,Telepon,Website,Keyword
0,ChIJeXbyGyGPcC4Rg7-5wOCeOeA,Bakmi Tantjap Tembalang,"Area NJ Guest House, Jl. Jatimulyo No.9 Lt. 2,...",Restoran,4.8,360,Senin: 10.00–23.30 | Selasa: 10.00–23.30 | Rab...,25000.0,50000.0,-7.056966,110.433502,0851-3858-4778,NaN,bakmi
1,ChIJ5WOtWQCPcC4RedscHY-t5fw,Bakmi Serangkai Tembalang,"Jl. Mulawarman Raya No.11, Pedalangan, Kec. Ba...",Restoran Mie,4.4,81,Senin: 12.00–01.00 | Selasa: 12.00–01.00 | Rab...,25000.0,50000.0,-7.068295,110.433887,0822-2527-1048,NaN,bakmi
2,ChIJTYgZCgCNcC4RmHHSNBKPfYs,Bakmi Polsek Nasihuy Cabang tembalang,"WCWJ+8HX, Jl. Prof. Soedarto, Pedalangan, Kec....",Restoran Indonesia,5.0,3,Senin: Buka 24 jam | Selasa: Buka 24 jam | Rab...,NaN,NaN,-7.054133,110.431475,NaN,NaN,bakmi
3,ChIJhaPc7XaPcC4RjRquGAb9kQE,Bakmi Surabaya Cak Dul 2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec...",Restoran Mie,4.0,495,Senin: 07.30–23.30 | Selasa: 07.30–23.30 | Rab...,1.0,25000.0,-7.068204,110.437274,0821-3400-6730,NaN,bakmi
4,ChIJtXUqbImPcC4RdXRvTOFnNlY,BAKSU (Bakmie & Katsu),"Jl. Timoho Bar. III No.38, Bulusan, Kec. Temba...",Restoran Mie,4.3,144,Senin: 09.00–21.00 | Selasa: 09.00–21.00 | Rab...,1.0,25000.0,-7.057076,110.444335,0895-3605-97975,NaN,bakmi

In [29]:
df.shape

(87, 14)

In [43]:
df.dtypes

Place ID            object
Nama Tempat         object
Alamat              object
Jenis Bisnis        object
Rating             float64
Jumlah Review        int64
Jam Operasional     object
Harga Start        float64
Harga End          float64
Latitude           float64
Longitude          float64
Telepon             object
Website             object
Keyword             object
Jalan               object
Kelurahan           object
Kecamatan           object
Kota                object
Provinsi            object
dtype: object

In [30]:
df['Harga Start'].value_counts()

Harga Start
1.0        41
25000.0    20
50000.0     3
75000.0     1
Name: count, dtype: int64

In [41]:
df.duplicated().any()

np.False_

In [31]:
df.isna().sum()

Place ID            0
Nama Tempat         0
Alamat              0
Jenis Bisnis        0
Rating              0
Jumlah Review       0
Jam Operasional     3
Harga Start        22
Harga End          22
Latitude            0
Longitude           0
Telepon            27
Website            77
Keyword             0
dtype: int64

In [32]:
df['Alamat'].unique()

array(['Area NJ Guest House, Jl. Jatimulyo No.9 Lt. 2, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Mulawarman Raya No.11, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50264, Indonesia',
       'WCWJ+8HX, Jl. Prof. Soedarto, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Mulawarman Selatan Raya No.18, Kramas, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278, Indonesia',
       'Jl. Timoho Bar. III No.38, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277, Indonesia',
       'Jl. Banjarsari Raya Tembalang No.44, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia',
       'Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276, Indonesia',
       'WCVP+V7G, Jl. Prof. Soedarto, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia',
       'XF4F+PXX, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Adi Patiunus No.16-2, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia',
       'Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'Jl baskoro no, 75, RT.3/RW.7, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia',
       'Depan SDIT Tunas Harapan, Ruko Mutiara Gading A4, Jl. Ketileng Indah Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Kompol R. Sukamto, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276, Indonesia',
       'WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277, Indonesia',
       'XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Banjarsari Selatan No.10, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Gayamsari Selatan I No.47, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50248, Indonesia',
       'Jl. Kompol R. Soekanto, kota, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Klipang Raya Permai Blok G23, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Blok D No, Jl. Klipang Raya Blk. G No.6, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50274, Indonesia',
       'XFG5+P9F, Jalan Jl. Kedungmundu, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'Jl. Veteran No.3A, Lempongsari, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50196, Indonesia',
       'XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Gerungsari No.26, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277, Indonesia',
       'XFM8+HM8, Jl. Amposari Raya, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'XF3F+VP9, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Gondang Barat I No.7, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277, Indonesia',
       'Jl. Sambiroto Raya No.6, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276, Indonesia',
       'Depas puskesmas Jl. Kompol R Soekanto, Mangunharjo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Klipang Raya No.26, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'Ruko, Ruko AD, Jl. Bukit Kencana Jaya Jl. Boulevard No.25, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'XFF5+9Q6, Jl. Sambiroto Raya, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276, Indonesia',
       'Jalan Prof. Suharso ,Meteseh, Tembalang, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'Jl. Dinar Elok Raya No.K2 No.5, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'Jl. Majapahit No.299, Gemah, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50246, Indonesia',
       'Jl. Kedungmundu No.169, Sendangguwo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'XCQR+XQ7, Gg. X, Lamper Tengah, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50248, Indonesia',
       'Jl. Beteng No.117, Kranggan, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50139, Indonesia',
       'XFRC+X7M, Jl. Pedurungan Tengah 6, Palebon, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50246, Indonesia',
       'Jl. Sompok Baru No.69, Lamper Kidul, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50249, Indonesia',
       'Graha Metro No.12B Blk B, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'Jl. Fatmawati No.175, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Kedungmu, Jl. Kedungmundu, Tandang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'Jl. Sambiroto Raya No.45A, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276, Indonesia',
       'perum klipang Blk. P XIV, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Sawunggaling III No.44, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Majapahit No.105, Pandean Lamper, Kec. Gayamsari, Kota Semarang, Jawa Tengah 50249, Indonesia',
       'Jl. Tegal Kangkung 14 No.224, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'XFG6+25P, Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah 50276, Indonesia',
       'Jl. Bukit Klp. Gading I No.32, Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia',
       'Jl. Kedungmundu No.510A, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMeteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277, Indonesia',
       'XFC9+W3W, Jl. Ketileng Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Banjarsari No.24, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia',
       'Jl. Jatimulyo No.12, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Majapahit, Palebon, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50192, Indonesia',
       'Jl. Bumirejo Raya, Gedawang, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50266, Indonesia',
       'Ruko Durian. 71, Jl. Durian Raya No.RT 08, RW I, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Gondang Raya No.33, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50277, Indonesia',
       'Jl. Mulawarman Tim. Dalam No.78, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50278, Indonesia',
       'Sambiroto, Kec. Tembalang, Kota Semarang, Jawa Tengah, Indonesia',
       'Jl. Wolter Monginsidi No.645, Pedurungan Tengah, Kec. Pedurungan, Kota Semarang, Jawa Tengah 50192, Indonesia',
       'Jl. KH. Sirojudin No.22A, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia',
       'Jl. Timoho Raya, Bulusan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Kedungmundu No.250, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'Jl. Tirto Agung No.64, Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Fatmawati No.177, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50246, Indonesia',
       'Ruko Kampung Jl. Semawis Raya No.16 Blk. A, Kedungmundu, Kec. Tembalang, Kota Semarang, Jawa Tengah 50273, Indonesia',
       'Jl. Jatimulyo No.5A, Pedalangan, Kec. Tembalang, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'Jl. Gajahmada No.123, Pekunden, Kec. Semarang Tengah, Kota Semarang, Jawa Tengah 50134, Indonesia',
       'Ruko Klipang Niaga No.3, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Ahmad Yani No.167 A lantai 2, Pleburan, Kec. Semarang Sel., Kota Semarang, Jawa Tengah 50241, Indonesia',
       'XF8F+FFR, Jl. Perumahan Ketileng Indah, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jl. Kelud Raya No.32a, Sampangan, Kec. Gajahmungkur, Kota Semarang, Jawa Tengah 50327, Indonesia',
       'Jl. Letjen Suprapto No.61, Kota Lama Semarang, Kec. Semarang Utara, Kota Semarang, Jawa Tengah 50137, Indonesia',
       'Jl. Banjarsari Selatan No.49B, Tembalang, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50268, Indonesia',
       'XF6F+XC6 Biru Depo Air Minum, Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang, Kota Semarang, Jawa Tengah 50272, Indonesia',
       'Jalan Bukit Sari Raya No. R-9, Sumurboto, Banyumanik, Ngesrep, Kec. Banyumanik, Kota Semarang, Jawa Tengah 50269, Indonesia',
       'Jl. Banjarsari No.29, Tembalang, Kec. Tembalang, Kota Semarang, Jawa Tengah 50275, Indonesia'],
      dtype=object)

In [33]:
def parse_alamat(alamat):
    if pd.isna(alamat):
        return pd.Series({
            "Jalan": None,
            "Kelurahan": None,
            "Kecamatan": None,
            "Kota": None,
            "Provinsi": None,
        })

    parts = [p.strip() for p in alamat.split(",")]

    # buang Indonesia
    if parts and parts[-1].lower() == "indonesia":
        parts.pop()

    provinsi = None
    kota = None
    kecamatan = None
    kelurahan = None
    jalan = None

    # Provinsi + kode pos
    # contoh: "Jawa Tengah 50196"
    if parts:
        provinsi_raw = parts.pop()
        provinsi = re.sub(r"\s+\d{5}$", "", provinsi_raw).strip()

    # Kota
    # contoh: "Kota Semarang"
    if parts and parts[-1].lower().startswith("kota "):
        kota = re.sub(
            r"^Kota\s+",
            "",
            parts.pop(),
            flags=re.IGNORECASE
        ).strip()

    # Kecamatan
    # contoh: "Kec. Tembalang"
    if parts and re.match(r"^Kec\.?\s+", parts[-1], re.IGNORECASE):
        kecamatan = re.sub(
            r"^Kec\.?\s+",
            "",
            parts.pop(),
            flags=re.IGNORECASE
        ).strip()

    # Segmen tepat sebelum kecamatan = kelurahan
    if parts:
        kelurahan = parts.pop().strip()

    # Semua sisanya dianggap Jalan / detail lokasi
    if parts:
        jalan = ", ".join(parts)

    return pd.Series({
        "Jalan": jalan,
        "Kelurahan": kelurahan,
        "Kecamatan": kecamatan,
        "Kota": kota,
        "Provinsi": provinsi,
    })

In [34]:
df[
    ["Jalan", "Kelurahan", "Kecamatan", "Kota", "Provinsi"]
] = df["Alamat"].apply(parse_alamat)

In [35]:
df.head()

,Place ID,Nama Tempat,Alamat,Jenis Bisnis,Rating,Jumlah Review,Jam Operasional,Harga Start,Harga End,Latitude,Longitude,Telepon,Website,Keyword,Jalan,Kelurahan,Kecamatan,Kota,Provinsi
0,ChIJeXbyGyGPcC4Rg7-5wOCeOeA,Bakmi Tantjap Tembalang,"Area NJ Guest House, Jl. Jatimulyo No.9 Lt. 2,...",Restoran,4.8,360,Senin: 10.00–23.30 | Selasa: 10.00–23.30 | Rab...,25000.0,50000.0,-7.056966,110.433502,0851-3858-4778,NaN,bakmi,"Area NJ Guest House, Jl. Jatimulyo No.9 Lt. 2",Pedalangan,Banyumanik,Semarang,Jawa Tengah
1,ChIJ5WOtWQCPcC4RedscHY-t5fw,Bakmi Serangkai Tembalang,"Jl. Mulawarman Raya No.11, Pedalangan, Kec. Ba...",Restoran Mie,4.4,81,Senin: 12.00–01.00 | Selasa: 12.00–01.00 | Rab...,25000.0,50000.0,-7.068295,110.433887,0822-2527-1048,NaN,bakmi,Jl. Mulawarman Raya No.11,Pedalangan,Banyumanik,Semarang,Jawa Tengah
2,ChIJTYgZCgCNcC4RmHHSNBKPfYs,Bakmi Polsek Nasihuy Cabang tembalang,"WCWJ+8HX, Jl. Prof. Soedarto, Pedalangan, Kec....",Restoran Indonesia,5.0,3,Senin: Buka 24 jam | Selasa: Buka 24 jam | Rab...,NaN,NaN,-7.054133,110.431475,NaN,NaN,bakmi,"WCWJ+8HX, Jl. Prof. Soedarto",Pedalangan,Banyumanik,Semarang,Jawa Tengah
3,ChIJhaPc7XaPcC4RjRquGAb9kQE,Bakmi Surabaya Cak Dul 2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec...",Restoran Mie,4.0,495,Senin: 07.30–23.30 | Selasa: 07.30–23.30 | Rab...,1.0,25000.0,-7.068204,110.437274,0821-3400-6730,NaN,bakmi,Jl. Mulawarman Selatan Raya No.18,Kramas,Tembalang,Semarang,Jawa Tengah
4,ChIJtXUqbImPcC4RdXRvTOFnNlY,BAKSU (Bakmie & Katsu),"Jl. Timoho Bar. III No.38, Bulusan, Kec. Temba...",Restoran Mie,4.3,144,Senin: 09.00–21.00 | Selasa: 09.00–21.00 | Rab...,1.0,25000.0,-7.057076,110.444335,0895-3605-97975,NaN,bakmi,Jl. Timoho Bar. III No.38,Bulusan,Tembalang,Semarang,Jawa Tengah

In [36]:
df = df[df['Kecamatan'] == 'Tembalang']

In [37]:
df.head()

,Place ID,Nama Tempat,Alamat,Jenis Bisnis,Rating,Jumlah Review,Jam Operasional,Harga Start,Harga End,Latitude,Longitude,Telepon,Website,Keyword,Jalan,Kelurahan,Kecamatan,Kota,Provinsi
3,ChIJhaPc7XaPcC4RjRquGAb9kQE,Bakmi Surabaya Cak Dul 2,"Jl. Mulawarman Selatan Raya No.18, Kramas, Kec...",Restoran Mie,4.0,495,Senin: 07.30–23.30 | Selasa: 07.30–23.30 | Rab...,1.0,25000.0,-7.068204,110.437274,0821-3400-6730,NaN,bakmi,Jl. Mulawarman Selatan Raya No.18,Kramas,Tembalang,Semarang,Jawa Tengah
4,ChIJtXUqbImPcC4RdXRvTOFnNlY,BAKSU (Bakmie & Katsu),"Jl. Timoho Bar. III No.38, Bulusan, Kec. Temba...",Restoran Mie,4.3,144,Senin: 09.00–21.00 | Selasa: 09.00–21.00 | Rab...,1.0,25000.0,-7.057076,110.444335,0895-3605-97975,NaN,bakmi,Jl. Timoho Bar. III No.38,Bulusan,Tembalang,Semarang,Jawa Tengah
5,ChIJJatTaFuPcC4RgzWs9JqpT4w,"Pondok Bakmie Surabaya ""Cak Dul""","Jl. Banjarsari Raya Tembalang No.44, Tembalang...",Restoran Mie,3.4,64,Senin: 07.00–23.30 | Selasa: 07.00–23.30 | Rab...,1.0,25000.0,-7.059733,110.440100,0813-2803-2121,NaN,bakmi,Jl. Banjarsari Raya Tembalang No.44,Tembalang,Tembalang,Semarang,Jawa Tengah
6,ChIJ6c-rHNeNcC4RxFrb1LRitnY,Bakmi Juned,"Jl. Sambiroto, Kedungmundu, Kec. Tembalang, Ko...",Restoran Mie,4.7,158,Senin: Tutup | Selasa: 17.00–00.00 | Rabu: 17....,1.0,25000.0,-7.024015,110.458790,NaN,NaN,bakmi,Jl. Sambiroto,Kedungmundu,Tembalang,Semarang,Jawa Tengah
7,ChIJecbeHbSNcC4R8qA_dqzD6_0,Bakmi Jowo Pak Pardi,"WCVP+V7G, Jl. Prof. Soedarto, Tembalang, Kec. ...",Restoran Mie,4.5,73,Senin: 17.30–23.00 | Selasa: 17.30–23.00 | Rab...,1.0,25000.0,-7.055324,110.435704,NaN,NaN,bakmi,"WCVP+V7G, Jl. Prof. Soedarto",Tembalang,Tembalang,Semarang,Jawa Tengah

In [38]:
df.shape

(63, 19)

In [42]:
df[df["Harga Start"].isna()]

,Place ID,Nama Tempat,Alamat,Jenis Bisnis,Rating,Jumlah Review,Jam Operasional,Harga Start,Harga End,Latitude,Longitude,Telepon,Website,Keyword,Jalan,Kelurahan,Kecamatan,Kota,Provinsi
9,ChIJQx9PIwCNcC4R_y1_VUp6Slw,Bakmie Polsek Nasihuy cabang tembalang,"Jl. Adi Patiunus No.16-2, Tembalang, Kec. Temb...",Restoran Indonesia,5.0,1,Senin: Buka 24 jam | Selasa: Buka 24 jam | Rab...,NaN,NaN,-7.055036,110.434693,NaN,NaN,bakmi,Jl. Adi Patiunus No.16-2,Tembalang,Tembalang,Semarang,Jawa Tengah
14,ChIJtd7IDgCPcC4RDenSnPjmk18,PONDOK Bakmi Surabaya Cak DUL,"WFV7+478, Jl. Profesor Suharso, Meteseh, Kec. ...",Warung Makanan Kecil,3.9,14,Senin: 16.00–23.00 | Selasa: 16.00–23.00 | Rab...,NaN,NaN,-7.057205,110.463189,0813-2515-7257,NaN,bakmi,"WFV7+478, Jl. Profesor Suharso",Meteseh,Tembalang,Semarang,Jawa Tengah
15,ChIJrSiv_0uMcC4R7u6wqeW5U2k,Bakmi Surabaya Cak Baron,"XFC9+768, Jl. Ketileng Raya, Sendangmulyo, Kec...",Restoran Mie,4.6,27,Senin: 18.45–23.45 | Selasa: 18.45–23.45 | Rab...,NaN,NaN,-7.029325,110.468078,NaN,NaN,bakmi,"XFC9+768, Jl. Ketileng Raya",Sendangmulyo,Tembalang,Semarang,Jawa Tengah
21,ChIJoVUk1V2NcC4RLXWsQyrPNgQ,BAKMI JOWO KANG DOEL,"XFH4+HPR, Kedungmundu, Kec. Tembalang, Kota Se...",Restoran Mie,4.9,16,Senin: 15.30–23.30 | Selasa: 15.30–23.30 | Rab...,NaN,NaN,-7.021003,110.456780,0812-2556-0512,NaN,bakmi,XFH4+HPR,Kedungmundu,Tembalang,Semarang,Jawa Tengah
24,ChIJ6fMwdzaMcC4R8Y2y6XRoDio,Bakmi Jowo Mas Agus,"XF69+X82, Jl. Gendong Raya, Mangunharjo, Kec. ...",Restoran Mie,4.6,29,Senin: 17.00–00.00 | Selasa: 17.00–00.00 | Rab...,NaN,NaN,-7.037619,110.468281,0819-0437-2937,NaN,bakmi,"XF69+X82, Jl. Gendong Raya",Mangunharjo,Tembalang,Semarang,Jawa Tengah
27,ChIJJxgFttKNcC4RQ8rAtfeapGY,bakmi surabaya cak yanto,"XF3F+VP9, Sendangmulyo, Kec. Tembalang, Kota S...",Restoran Mie,4.5,15,Senin: 17.00–22.00 | Selasa: 17.00–22.00 | Rab...,NaN,NaN,-7.045329,110.474352,0895-3367-24891,NaN,bakmi,XF3F+VP9,Sendangmulyo,Tembalang,Semarang,Jawa Tengah
29,ChIJrQVc_UaMcC4RTZfwIkFLgi4,Bakmi Jowo Mas Agus,"Jl. Sambiroto Raya No.6, Sambiroto, Kec. Temba...",Restoran Mie,4.5,99,Senin: 17.00–02.00 | Selasa: 17.00–02.00 | Rab...,NaN,NaN,-7.032360,110.458110,0858-0213-9915,NaN,bakmi,Jl. Sambiroto Raya No.6,Sambiroto,Tembalang,Semarang,Jawa Tengah
32,ChIJJxXt44COcC4RctS71K6-h98,Bakmi Surabaya,"Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Ra...",Restoran Mie,3.8,10,Senin: 17.00–00.00 | Selasa: 17.00–00.00 | Rab...,NaN,NaN,-7.058050,110.471033,0813-2669-4979,NaN,bakmi,"Jalan Rowosari Raya, Jl. Talang Jl. Baskoro Raya",Meteseh,Tembalang,Semarang,Jawa Tengah
34,ChIJ3Z0aT0SNcC4R5DYgdoElS6I,"BAKMI SUROBOYO MAS NDUT (YUDI),METESEH","Jl. Raya Sendangmulyo, Meteseh, Kec. Tembalang...",Restoran Mie,4.3,8,Senin: 17.30–23.00 | Selasa: 17.30–23.00 | Rab...,NaN,NaN,-7.052854,110.471467,0878-3106-0032,NaN,bakmi,Jl. Raya Sendangmulyo,Meteseh,Tembalang,Semarang,Jawa Tengah
39,ChIJKQGsi8CNcC4RMUH7EycP9o0,bakmie surabaya mas allfa99,"Jl. Kedungmundu No.169, Sendangguwo, Kec. Temb...",Konsultan,5.0,3,Senin: 17.00–23.00 | Selasa: 16.30–23.30 | Rab...,NaN,NaN,-7.013551,110.451746,0822-2408-0549,http://grabfood.co.id/,bakmi,Jl. Kedungmundu No.169,Sendangguwo,Tembalang,Semarang,Jawa Tengah
45,ChIJ_VHlvsiNcC4RcqfwTM81Q1g,Warung TUMAN - Nasi Goreng & Bakmi Tuman,"Meteseh, Kec. Tembalang, Kota Semarang, Jawa T...",Restoran Indonesia,5.0,12,Senin: 17.00–22.00 | Selasa: 17.00–22.00 | Rab...,NaN,NaN,-7.053261,110.477665,NaN,https://id.shp.ee/ehq3wrw?smtt=0.0.9,bakmi,None,Meteseh,Tembalang,Semarang,Jawa Tengah
46,ChIJnxdaBlOMcC4RGNV3jIigBFU,Bakmie Suroboyo,"XFHC+JFF, Jl. Mukharom, Kedungmundu, Kec. Temb...",Restoran Mie,4.6,5,Senin: 12.00–22.00 | Selasa: 12.00–22.00 | Rab...,NaN,NaN,-7.020926,110.471160,NaN,NaN,bakmi,"XFHC+JFF, Jl. Mukharom",Kedungmundu,Tembalang,Semarang,Jawa Tengah
48,ChIJOz7UdMuNcC4RpKko4wYW-S8,Bakmi jowo pak wito,"Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang...",Restoran Asia,3.9,16,Senin: 17.00–01.00 | Selasa: 17.00–01.00 | Rab...,NaN,NaN,-7.037739,110.476659,0851-0010-6508,NaN,bakmi,Jl. Klipang Raya,Sendangmulyo,Tembalang,Semarang,Jawa Tengah
54,ChIJ3ZBU25KNcC4RqB11HGOBSl4,Bakmi Jowo Sederhana,"Jl. Tegal Kangkung 14 No.224, Kedungmundu, Kec...",Restoran Mie,4.3,4,Senin: 18.00–00.00 | Selasa: 18.00–00.00 | Rab...,NaN,NaN,-7.023244,110.468932,NaN,NaN,bakmi,Jl. Tegal Kangkung 14 No.224,Kedungmundu,Tembalang,Semarang,Jawa Tengah
55,ChIJfTRjMEWMcC4Rj2KUGiM1VN4,Bakmi Jowo Pak No,"XFG6+25P, Sambiroto, Kec. Tembalang, Kota Sema...",Restoran Mie,3.8,4,Senin: 04.00–01.00 | Selasa: 04.00–01.00 | Rab...,NaN,NaN,-7.024920,110.460452,0857-9916-0449,NaN,bakmi,XFG6+25P,Sambiroto,Tembalang,Semarang,Jawa Tengah
56,ChIJ3zL5RrCPcC4RiHPrpizskyI,Bakmi Jowo Pak Sis - Meteseh,"Jl. Bukit Klp. Gading I No.32, Meteseh, Kec. T...",Restoran Mie,5.0,1,Senin: 17.00–00.00 | Selasa: 17.00–00.00 | Rab...,NaN,NaN,-7.065751,110.459820,0822-2096-6500,NaN,bakmi,Jl. Bukit Klp. Gading I No.32,Meteseh,Tembalang,Semarang,Jawa Tengah
58,ChIJH-KpBwCPcC4RwEjvXtXhZc8,Pondok Bakmi Surabaya Cakdul Meteseh,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana, JayaMetes...",Restoran Indonesia,5.0,2,NaN,NaN,NaN,-7.060934,110.462336,NaN,NaN,bakmi,"WFQ6+JWG, WFV7+46GJl. Bukit Kencana",JayaMeteseh,Tembalang,Semarang,Jawa Tengah
79,ChIJRxkHrEqMcC4RuCGDJxTh3Q0,Nori House,"XF8F+FFR, Jl. Perumahan Ketileng Indah, Sendan...",Restoran,4.8,25,Senin: 10.30–21.00 | Selasa: 10.30–21.00 | Rab...,NaN,NaN,-7.033755,110.473628,NaN,NaN,ramen,"XF8F+FFR, Jl. Perumahan Ketileng Indah",Sendangmulyo,Tembalang,Semarang,Jawa Tengah
81,ChIJn_1qYemNcC4RQVCRsmMQ5LI,Pak MOE Katsu dan Mie Ramen,"Jl. Klipang Raya, Sendangmulyo, Kec. Tembalang...",Restoran,5.0,3,Senin: 15.30–21.00 | Selasa: 15.30–21.00 | Rab...,NaN,NaN,-7.037669,110.479128,0812-2509-7097,NaN,ramen,Jl. Klipang Raya,Sendangmulyo,Tembalang,Semarang,Jawa Tengah
84,ChIJ_bqKBBiNcC4ROlbRDdvS2qY,Hambagu Japan Steak Rice,"XF6F+XC6 Biru Depo Air Minum, Jl. Klipang Raya...",Restoran Jepang,4.7,3,Senin: 10.00–22.00 | Selasa: 10.00–22.00 | Rab...,NaN,NaN,-7.037584,110.473511,NaN,NaN,ramen,"XF6F+XC6 Biru Depo Air Minum, Jl. Klipang Raya",Sendangmulyo,Tembalang,Semarang,Jawa Tengah

In [44]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(r"\s+", "_", regex=True)
)

print("Columns:")
print(df.columns.tolist())

Columns:
['place_id', 'nama_tempat', 'alamat', 'jenis_bisnis', 'rating', 'jumlah_review', 'jam_operasional', 'harga_start', 'harga_end', 'latitude', 'longitude', 'telepon', 'website', 'keyword', 'jalan', 'kelurahan', 'kecamatan', 'kota', 'provinsi']

In [45]:
print("\nMissing values:")
print(df.isna().sum())

print("\nData types:")
print(df.dtypes)

Missing values:
place_id            0
nama_tempat         0
alamat              0
jenis_bisnis        0
rating              0
jumlah_review       0
jam_operasional     3
harga_start        20
harga_end          20
latitude            0
longitude           0
telepon            20
website            60
keyword             0
jalan               3
kelurahan           0
kecamatan           0
kota                0
provinsi            0
dtype: int64

Data types:
place_id            object
nama_tempat         object
alamat              object
jenis_bisnis        object
rating             float64
jumlah_review        int64
jam_operasional     object
harga_start        float64
harga_end          float64
latitude           float64
longitude          float64
telepon             object
website             object
keyword             object
jalan               object
kelurahan           object
kecamatan           object
kota                object
provinsi            object
dtype: object

In [46]:
df.to_csv(
    "clean_data.csv",
    index=False,
    encoding="utf-8-sig"
)